M48
; DRILL file {KiCad 9.0.7} date 2026-04-14T08:08:07-0700
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-04-14T08:08:07-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.550
%
G90
G05
T1
X30.7Y-24.1
X30.7Y-90.6
X129.2Y-24.1
X129.2Y-90.6
T2
X50.54Y-88.157
X71.37Y-88.157
M30
